// JavaScript Document





function makeRooms()
{

function ReplaceContentInContainer(SnarF, FranS) {
  var nodeList = document.getElementsByClassName(SnarF);console.info(nodeList[0]);
  for (var i = 0, length = nodeList.length; i < length; i++) {
     nodeList[i].innerHTML = FranS;
  }
}


/*
The words for the rooms are in another file now.
*/

/*
These assign room type and adj to each room
*/

var room2adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room3adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room4adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room5adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room6adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room7adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room8adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room9adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room10adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room11adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room12adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room13adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room14adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room15adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room16adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room17adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room18adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room19adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room20adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room21adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room22adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room23adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room24adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room25adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room26adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room27adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room28adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room29adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room30adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room31adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room32adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room33adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room34adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room35adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room36adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room37adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room38adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room39adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room40adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room41adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room42adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room43adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room44adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room45adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room46adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room47adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room48adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room49adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room50adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room51adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room52adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room53adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room54adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room55adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room56adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room57adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room58adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room59adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room60adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room61adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room62adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room63adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room64adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room65adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room66adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room67adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room68adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room69adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room70adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room71adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room72adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room73adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room74adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room75adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room76adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room77adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room78adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room79adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room80adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room81adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room82adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room83adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room84adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room85adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room86adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room87adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room88adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room89adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room90adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room91adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room92adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room93adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room94adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room95adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room96adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room97adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room98adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room99adj=rAdj[Math.floor(Math.random() * rAdj.length)];
var room100adj=rAdj[Math.floor(Math.random() * rAdj.length)];
console.info('adj');

var room2type=rType[Math.floor(Math.random() * rType.length)];
var room3type=rType[Math.floor(Math.random() * rType.length)];
var room4type=rType[Math.floor(Math.random() * rType.length)];
var room5type=rType[Math.floor(Math.random() * rType.length)];
var room6type=rType[Math.floor(Math.random() * rType.length)];
var room7type=rType[Math.floor(Math.random() * rType.length)];
var room8type=rType[Math.floor(Math.random() * rType.length)];
var room9type=rType[Math.floor(Math.random() * rType.length)];
var room10type=rType[Math.floor(Math.random() * rType.length)];
var room11type=rType[Math.floor(Math.random() * rType.length)];
var room12type=rType[Math.floor(Math.random() * rType.length)];
var room13type=rType[Math.floor(Math.random() * rType.length)];
var room14type=rType[Math.floor(Math.random() * rType.length)];
var room15type=rType[Math.floor(Math.random() * rType.length)];
var room16type=rType[Math.floor(Math.random() * rType.length)];
var room17type=rType[Math.floor(Math.random() * rType.length)];
var room18type=rType[Math.floor(Math.random() * rType.length)];
var room19type=rType[Math.floor(Math.random() * rType.length)];
var room20type=rType[Math.floor(Math.random() * rType.length)];
var room21type=rType[Math.floor(Math.random() * rType.length)];
var room22type=rType[Math.floor(Math.random() * rType.length)];
var room23type=rType[Math.floor(Math.random() * rType.length)];
var room24type=rType[Math.floor(Math.random() * rType.length)];
var room25type=rType[Math.floor(Math.random() * rType.length)];
var room26type=rType[Math.floor(Math.random() * rType.length)];
var room27type=rType[Math.floor(Math.random() * rType.length)];
var room28type=rType[Math.floor(Math.random() * rType.length)];
var room29type=rType[Math.floor(Math.random() * rType.length)];
var room30type=rType[Math.floor(Math.random() * rType.length)];
var room31type=rType[Math.floor(Math.random() * rType.length)];
var room32type=rType[Math.floor(Math.random() * rType.length)];
var room33type=rType[Math.floor(Math.random() * rType.length)];
var room34type=rType[Math.floor(Math.random() * rType.length)];
var room35type=rType[Math.floor(Math.random() * rType.length)];
var room36type=rType[Math.floor(Math.random() * rType.length)];
var room37type=rType[Math.floor(Math.random() * rType.length)];
var room38type=rType[Math.floor(Math.random() * rType.length)];
var room39type=rType[Math.floor(Math.random() * rType.length)];
var room40type=rType[Math.floor(Math.random() * rType.length)];
var room41type=rType[Math.floor(Math.random() * rType.length)];
var room42type=rType[Math.floor(Math.random() * rType.length)];
var room43type=rType[Math.floor(Math.random() * rType.length)];
var room44type=rType[Math.floor(Math.random() * rType.length)];
var room45type=rType[Math.floor(Math.random() * rType.length)];
var room46type=rType[Math.floor(Math.random() * rType.length)];
var room47type=rType[Math.floor(Math.random() * rType.length)];
var room48type=rType[Math.floor(Math.random() * rType.length)];
var room49type=rType[Math.floor(Math.random() * rType.length)];
var room50type=rType[Math.floor(Math.random() * rType.length)];
var room51type=rType[Math.floor(Math.random() * rType.length)];
var room52type=rType[Math.floor(Math.random() * rType.length)];
var room53type=rType[Math.floor(Math.random() * rType.length)];
var room54type=rType[Math.floor(Math.random() * rType.length)];
var room55type=rType[Math.floor(Math.random() * rType.length)];
var room56type=rType[Math.floor(Math.random() * rType.length)];
var room57type=rType[Math.floor(Math.random() * rType.length)];
var room58type=rType[Math.floor(Math.random() * rType.length)];
var room59type=rType[Math.floor(Math.random() * rType.length)];
var room60type=rType[Math.floor(Math.random() * rType.length)];
var room61type=rType[Math.floor(Math.random() * rType.length)];
var room62type=rType[Math.floor(Math.random() * rType.length)];
var room63type=rType[Math.floor(Math.random() * rType.length)];
var room64type=rType[Math.floor(Math.random() * rType.length)];
var room65type=rType[Math.floor(Math.random() * rType.length)];
var room66type=rType[Math.floor(Math.random() * rType.length)];
var room67type=rType[Math.floor(Math.random() * rType.length)];
var room68type=rType[Math.floor(Math.random() * rType.length)];
var room69type=rType[Math.floor(Math.random() * rType.length)];
var room70type=rType[Math.floor(Math.random() * rType.length)];
var room71type=rType[Math.floor(Math.random() * rType.length)];
var room72type=rType[Math.floor(Math.random() * rType.length)];
var room73type=rType[Math.floor(Math.random() * rType.length)];
var room74type=rType[Math.floor(Math.random() * rType.length)];
var room75type=rType[Math.floor(Math.random() * rType.length)];
var room76type=rType[Math.floor(Math.random() * rType.length)];
var room77type=rType[Math.floor(Math.random() * rType.length)];
var room78type=rType[Math.floor(Math.random() * rType.length)];
var room79type=rType[Math.floor(Math.random() * rType.length)];
var room80type=rType[Math.floor(Math.random() * rType.length)];
var room81type=rType[Math.floor(Math.random() * rType.length)];
var room82type=rType[Math.floor(Math.random() * rType.length)];
var room83type=rType[Math.floor(Math.random() * rType.length)];
var room84type=rType[Math.floor(Math.random() * rType.length)];
var room85type=rType[Math.floor(Math.random() * rType.length)];
var room86type=rType[Math.floor(Math.random() * rType.length)];
var room87type=rType[Math.floor(Math.random() * rType.length)];
var room88type=rType[Math.floor(Math.random() * rType.length)];
var room89type=rType[Math.floor(Math.random() * rType.length)];
var room90type=rType[Math.floor(Math.random() * rType.length)];
var room91type=rType[Math.floor(Math.random() * rType.length)];
var room92type=rType[Math.floor(Math.random() * rType.length)];
var room93type=rType[Math.floor(Math.random() * rType.length)];
var room94type=rType[Math.floor(Math.random() * rType.length)];
var room95type=rType[Math.floor(Math.random() * rType.length)];
var room96type=rType[Math.floor(Math.random() * rType.length)];
var room97type=rType[Math.floor(Math.random() * rType.length)];
var room98type=rType[Math.floor(Math.random() * rType.length)];
var room99type=rType[Math.floor(Math.random() * rType.length)];
var room100type=rType[Math.floor(Math.random() * rType.length)];
console.info('type'); 


/*
This puts them together
*/

var room2name=room2adj + " " + room2type;
var room3name=room3adj + " " + room3type;
var room4name=room4adj + " " + room4type;
var room5name=room5adj + " " + room5type;
var room6name=room6adj + " " + room6type;
var room7name=room7adj + " " + room7type;
var room8name=room8adj + " " + room8type;
var room9name=room9adj + " " + room9type;
var room10name=room10adj + " " + room10type;
var room11name=room11adj + " " + room11type;
var room12name=room12adj + " " + room12type;
var room13name=room13adj + " " + room13type;
var room14name=room14adj + " " + room14type;
var room15name=room15adj + " " + room15type;
var room16name=room16adj + " " + room16type;
var room17name=room17adj + " " + room17type;
var room18name=room18adj + " " + room18type;
var room19name=room19adj + " " + room19type;
var room20name=room20adj + " " + room20type;
var room21name=room21adj + " " + room21type;
var room22name=room22adj + " " + room22type;
var room23name=room23adj + " " + room23type;
var room24name=room24adj + " " + room24type;
var room25name=room25adj + " " + room25type;
var room26name=room26adj + " " + room26type;
var room27name=room27adj + " " + room27type;
var room28name=room28adj + " " + room28type;
var room29name=room29adj + " " + room29type;
var room30name=room30adj + " " + room30type;
var room31name=room31adj + " " + room31type;
var room32name=room32adj + " " + room32type;
var room33name=room33adj + " " + room33type;
var room34name=room34adj + " " + room34type;
var room35name=room35adj + " " + room35type;
var room36name=room36adj + " " + room36type;
var room37name=room37adj + " " + room37type;
var room38name=room38adj + " " + room38type;
var room39name=room39adj + " " + room39type;
var room40name=room40adj + " " + room40type;
var room41name=room41adj + " " + room41type;
var room42name=room42adj + " " + room42type;
var room43name=room43adj + " " + room43type;
var room44name=room44adj + " " + room44type;
var room45name=room45adj + " " + room45type;
var room46name=room46adj + " " + room46type;
var room47name=room47adj + " " + room47type;
var room48name=room48adj + " " + room48type;
var room49name=room49adj + " " + room49type;
var room50name=room50adj + " " + room50type;
var room51name=room51adj + " " + room51type;
var room52name=room52adj + " " + room52type;
var room53name=room53adj + " " + room53type;
var room54name=room54adj + " " + room54type;
var room55name=room55adj + " " + room55type;
var room56name=room56adj + " " + room56type;
var room57name=room57adj + " " + room57type;
var room58name=room58adj + " " + room58type;
var room59name=room59adj + " " + room59type;
var room60name=room60adj + " " + room60type;
var room61name=room61adj + " " + room61type;
var room62name=room62adj + " " + room62type;
var room63name=room63adj + " " + room63type;
var room64name=room64adj + " " + room64type;
var room65name=room65adj + " " + room65type;
var room66name=room66adj + " " + room66type;
var room67name=room67adj + " " + room67type;
var room68name=room68adj + " " + room68type;
var room69name=room69adj + " " + room69type;
var room70name=room70adj + " " + room70type;
var room71name=room71adj + " " + room71type;
var room72name=room72adj + " " + room72type;
var room73name=room73adj + " " + room73type;
var room74name=room74adj + " " + room74type;
var room75name=room75adj + " " + room75type;
var room76name=room76adj + " " + room76type;
var room77name=room77adj + " " + room77type;
var room78name=room78adj + " " + room78type;
var room79name=room79adj + " " + room79type;
var room80name=room80adj + " " + room80type;
var room81name=room81adj + " " + room81type;
var room82name=room82adj + " " + room82type;
var room83name=room83adj + " " + room83type;
var room84name=room84adj + " " + room84type;
var room85name=room85adj + " " + room85type;
var room86name=room86adj + " " + room86type;
var room87name=room87adj + " " + room87type;
var room88name=room88adj + " " + room88type;
var room89name=room89adj + " " + room89type;
var room90name=room90adj + " " + room90type;
var room91name=room91adj + " " + room91type;
var room92name=room92adj + " " + room92type;
var room93name=room93adj + " " + room93type;
var room94name=room94adj + " " + room94type;
var room95name=room95adj + " " + room95type;
var room96name=room96adj + " " + room96type;
var room97name=room97adj + " " + room97type;
var room98name=room98adj + " " + room98type;
var room99name=room99adj + " " + room99type;
var room100name=room100adj + " " + room100type;
console.info('name'); 



/*
This is the room text
*/

var room2desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room3desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room4desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room5desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room6desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room7desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room8desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room9desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room10desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room11desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room12desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room13desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room14desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room15desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room16desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room17desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room18desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room19desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room20desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room21desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room22desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room23desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room24desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room25desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room26desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room27desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room28desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room29desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room30desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room31desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room32desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room33desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room34desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room35desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room36desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room37desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room38desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room39desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room40desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room41desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room42desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room43desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room44desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room45desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room46desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room47desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room48desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room49desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room50desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room51desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room52desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room53desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room54desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room55desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room56desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room57desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room58desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room59desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room60desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room61desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room62desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room63desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room64desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room65desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room66desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room67desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room68desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room69desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room70desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room71desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room72desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room73desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room74desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room75desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room76desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room77desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room78desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room79desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room80desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room81desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room82desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room83desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room84desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room85desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room86desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room87desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room88desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room89desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room90desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room91desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room92desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room93desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room94desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room95desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room96desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room97desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room98desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room99desc=rDesc[Math.floor(Math.random() * rDesc.length)];
var room100desc=rDesc[Math.floor(Math.random() * rDesc.length)];
console.info('desc'); 

/*
This inserts the relevant text throughout the maze
*/



document.getElementById("room1text").innerHTML="<h1>Welcome to this maze</h1>  <p>I think you should be making your way towards the " + room100name + ".</p>";

document.getElementById("room2text").innerHTML="<h1>The " + room2name + "</h1>" + room2desc;
document.getElementById("room3text").innerHTML="<h1>The " + room3name + "</h1>" + room3desc;
document.getElementById("room4text").innerHTML="<h1>The " + room4name + "</h1>" + room4desc;
document.getElementById("room5text").innerHTML="<h1>The " + room5name + "</h1>" + room5desc;
document.getElementById("room6text").innerHTML="<h1>The " + room6name + "</h1>" + room6desc;
document.getElementById("room7text").innerHTML="<h1>The " + room7name + "</h1>" + room7desc;
document.getElementById("room8text").innerHTML="<h1>The " + room8name + "</h1>" + room8desc;
document.getElementById("room9text").innerHTML="<h1>The " + room9name + "</h1>" + room9desc;
document.getElementById("room10text").innerHTML="<h1>The " + room10name + "</h1>" + room10desc;
document.getElementById("room11text").innerHTML="<h1>The " + room11name + "</h1>" + room11desc;
document.getElementById("room12text").innerHTML="<h1>The " + room12name + "</h1>" + room12desc;
document.getElementById("room13text").innerHTML="<h1>The " + room13name + "</h1>" + room13desc;
document.getElementById("room14text").innerHTML="<h1>The " + room14name + "</h1>" + room14desc;
document.getElementById("room15text").innerHTML="<h1>The " + room15name + "</h1>" + room15desc;
document.getElementById("room16text").innerHTML="<h1>The " + room16name + "</h1>" + room16desc;
document.getElementById("room17text").innerHTML="<h1>The " + room17name + "</h1>" + room17desc;
document.getElementById("room18text").innerHTML="<h1>The " + room18name + "</h1>" + room18desc;
document.getElementById("room19text").innerHTML="<h1>The " + room19name + "</h1>" + room19desc;
document.getElementById("room20text").innerHTML="<h1>The " + room20name + "</h1>" + room20desc;
document.getElementById("room21text").innerHTML="<h1>The " + room21name + "</h1>" + room21desc;
document.getElementById("room22text").innerHTML="<h1>The " + room22name + "</h1>" + room22desc;
document.getElementById("room23text").innerHTML="<h1>The " + room23name + "</h1>" + room23desc;
document.getElementById("room24text").innerHTML="<h1>The " + room24name + "</h1>" + room24desc;
document.getElementById("room25text").innerHTML="<h1>The " + room25name + "</h1>" + room25desc;
document.getElementById("room26text").innerHTML="<h1>The " + room26name + "</h1>" + room26desc;
document.getElementById("room27text").innerHTML="<h1>The " + room27name + "</h1>" + room27desc;
document.getElementById("room28text").innerHTML="<h1>The " + room28name + "</h1>" + room28desc;
document.getElementById("room29text").innerHTML="<h1>The " + room29name + "</h1>" + room29desc;
document.getElementById("room30text").innerHTML="<h1>The " + room30name + "</h1>" + room30desc;
document.getElementById("room31text").innerHTML="<h1>The " + room31name + "</h1>" + room31desc;
document.getElementById("room32text").innerHTML="<h1>The " + room32name + "</h1>" + room32desc;
document.getElementById("room33text").innerHTML="<h1>The " + room33name + "</h1>" + room33desc;
document.getElementById("room34text").innerHTML="<h1>The " + room34name + "</h1>" + room34desc;
document.getElementById("room35text").innerHTML="<h1>The " + room35name + "</h1>" + room35desc;
document.getElementById("room36text").innerHTML="<h1>The " + room36name + "</h1>" + room36desc;
document.getElementById("room37text").innerHTML="<h1>The " + room37name + "</h1>" + room37desc;
document.getElementById("room38text").innerHTML="<h1>The " + room38name + "</h1>" + room38desc;
document.getElementById("room39text").innerHTML="<h1>The " + room39name + "</h1>" + room39desc;
document.getElementById("room40text").innerHTML="<h1>The " + room40name + "</h1>" + room40desc;
document.getElementById("room41text").innerHTML="<h1>The " + room41name + "</h1>" + room41desc;
document.getElementById("room42text").innerHTML="<h1>The " + room42name + "</h1>" + room42desc;
document.getElementById("room43text").innerHTML="<h1>The " + room43name + "</h1>" + room43desc;
document.getElementById("room44text").innerHTML="<h1>The " + room44name + "</h1>" + room44desc;
document.getElementById("room45text").innerHTML="<h1>The " + room45name + "</h1>" + room45desc;
document.getElementById("room46text").innerHTML="<h1>The " + room46name + "</h1>" + room46desc;
document.getElementById("room47text").innerHTML="<h1>The " + room47name + "</h1>" + room47desc;
document.getElementById("room48text").innerHTML="<h1>The " + room48name + "</h1>" + room48desc;
document.getElementById("room49text").innerHTML="<h1>The " + room49name + "</h1>" + room49desc;
document.getElementById("room50text").innerHTML="<h1>The " + room50name + "</h1>" + room50desc;
document.getElementById("room51text").innerHTML="<h1>The " + room51name + "</h1>" + room51desc;
document.getElementById("room52text").innerHTML="<h1>The " + room52name + "</h1>" + room52desc;
document.getElementById("room53text").innerHTML="<h1>The " + room53name + "</h1>" + room53desc;
document.getElementById("room54text").innerHTML="<h1>The " + room54name + "</h1>" + room54desc;
document.getElementById("room55text").innerHTML="<h1>The " + room55name + "</h1>" + room55desc;
document.getElementById("room56text").innerHTML="<h1>The " + room56name + "</h1>" + room56desc;
document.getElementById("room57text").innerHTML="<h1>The " + room57name + "</h1>" + room57desc;
document.getElementById("room58text").innerHTML="<h1>The " + room58name + "</h1>" + room58desc;
document.getElementById("room59text").innerHTML="<h1>The " + room59name + "</h1>" + room59desc;
document.getElementById("room60text").innerHTML="<h1>The " + room60name + "</h1>" + room60desc;
document.getElementById("room61text").innerHTML="<h1>The " + room61name + "</h1>" + room61desc;
document.getElementById("room62text").innerHTML="<h1>The " + room62name + "</h1>" + room62desc;
document.getElementById("room63text").innerHTML="<h1>The " + room63name + "</h1>" + room63desc;
document.getElementById("room64text").innerHTML="<h1>The " + room64name + "</h1>" + room64desc;
document.getElementById("room65text").innerHTML="<h1>The " + room65name + "</h1>" + room65desc;
document.getElementById("room66text").innerHTML="<h1>The " + room66name + "</h1>" + room66desc;
document.getElementById("room67text").innerHTML="<h1>The " + room67name + "</h1>" + room67desc;
document.getElementById("room68text").innerHTML="<h1>The " + room68name + "</h1>" + room68desc;
document.getElementById("room69text").innerHTML="<h1>The " + room69name + "</h1>" + room69desc;
document.getElementById("room70text").innerHTML="<h1>The " + room70name + "</h1>" + room70desc;
document.getElementById("room71text").innerHTML="<h1>The " + room71name + "</h1>" + room71desc;
document.getElementById("room72text").innerHTML="<h1>The " + room72name + "</h1>" + room72desc;
document.getElementById("room73text").innerHTML="<h1>The " + room73name + "</h1>" + room73desc;
document.getElementById("room74text").innerHTML="<h1>The " + room74name + "</h1>" + room74desc;
document.getElementById("room75text").innerHTML="<h1>The " + room75name + "</h1>" + room75desc;
document.getElementById("room76text").innerHTML="<h1>The " + room76name + "</h1>" + room76desc;
document.getElementById("room77text").innerHTML="<h1>The " + room77name + "</h1>" + room77desc;
document.getElementById("room78text").innerHTML="<h1>The " + room78name + "</h1>" + room78desc;
document.getElementById("room79text").innerHTML="<h1>The " + room79name + "</h1>" + room79desc;
document.getElementById("room80text").innerHTML="<h1>The " + room80name + "</h1>" + room80desc;
document.getElementById("room81text").innerHTML="<h1>The " + room81name + "</h1>" + room81desc;
document.getElementById("room82text").innerHTML="<h1>The " + room82name + "</h1>" + room82desc;
document.getElementById("room83text").innerHTML="<h1>The " + room83name + "</h1>" + room83desc;
document.getElementById("room84text").innerHTML="<h1>The " + room84name + "</h1>" + room84desc;
document.getElementById("room85text").innerHTML="<h1>The " + room85name + "</h1>" + room85desc;
document.getElementById("room86text").innerHTML="<h1>The " + room86name + "</h1>" + room86desc;
document.getElementById("room87text").innerHTML="<h1>The " + room87name + "</h1>" + room87desc;
document.getElementById("room88text").innerHTML="<h1>The " + room88name + "</h1>" + room88desc;
document.getElementById("room89text").innerHTML="<h1>The " + room89name + "</h1>" + room89desc;
document.getElementById("room90text").innerHTML="<h1>The " + room90name + "</h1>" + room90desc;
document.getElementById("room91text").innerHTML="<h1>The " + room91name + "</h1>" + room91desc;
document.getElementById("room92text").innerHTML="<h1>The " + room92name + "</h1>" + room92desc;
document.getElementById("room93text").innerHTML="<h1>The " + room93name + "</h1>" + room93desc;
document.getElementById("room94text").innerHTML="<h1>The " + room94name + "</h1>" + room94desc;
document.getElementById("room95text").innerHTML="<h1>The " + room95name + "</h1>" + room95desc;
document.getElementById("room96text").innerHTML="<h1>The " + room96name + "</h1>" + room96desc;
document.getElementById("room97text").innerHTML="<h1>The " + room97name + "</h1>" + room97desc;
document.getElementById("room98text").innerHTML="<h1>The " + room98name + "</h1>" + room98desc;
document.getElementById("room99text").innerHTML="<h1>The " + room99name + "</h1>" + room99desc;
document.getElementById("room100text").innerHTML="<h1>The " + room100name + "</h1>" + room100desc;
console.info('room text'); 

/*
These are the links
*/

ReplaceContentInContainer('room2link', room2name)
/*document.getElementsByClassName("room2link")[0].innerHTML=room2name;*/
console.info('one link'); 
document.getElementsByClassName("room3link")[0].innerHTML=room3name;
document.getElementsByClassName("room4link")[0].innerHTML=room4name;
document.getElementsByClassName("room5link")[0].innerHTML=room5name;
document.getElementsByClassName("room6link")[0].innerHTML=room6name;
document.getElementsByClassName("room7link")[0].innerHTML=room7name;
document.getElementsByClassName("room8link")[0].innerHTML=room8name;
document.getElementsByClassName("room9link")[0].innerHTML=room9name;
document.getElementsByClassName("room10link")[0].innerHTML=room10name;
document.getElementsByClassName("room11link")[0].innerHTML=room11name;
document.getElementsByClassName("room12link")[0].innerHTML=room12name;
document.getElementsByClassName("room13link")[0].innerHTML=room13name;
document.getElementsByClassName("room14link")[0].innerHTML=room14name;
document.getElementsByClassName("room15link")[0].innerHTML=room15name;
document.getElementsByClassName("room16link")[0].innerHTML=room16name;
document.getElementsByClassName("room17link")[0].innerHTML=room17name;
document.getElementsByClassName("room18link")[0].innerHTML=room18name;
document.getElementsByClassName("room19link")[0].innerHTML=room19name;
document.getElementsByClassName("room20link")[0].innerHTML=room20name;
document.getElementsByClassName("room21link")[0].innerHTML=room21name;
document.getElementsByClassName("room22link")[0].innerHTML=room22name;
document.getElementsByClassName("room23link")[0].innerHTML=room23name;
document.getElementsByClassName("room24link")[0].innerHTML=room24name;
document.getElementsByClassName("room25link")[0].innerHTML=room25name;
document.getElementsByClassName("room26link")[0].innerHTML=room26name;
document.getElementsByClassName("room27link")[0].innerHTML=room27name;
document.getElementsByClassName("room28link")[0].innerHTML=room28name;
document.getElementsByClassName("room29link")[0].innerHTML=room29name;
document.getElementsByClassName("room30link")[0].innerHTML=room30name;
document.getElementsByClassName("room31link")[0].innerHTML=room31name;
document.getElementsByClassName("room32link")[0].innerHTML=room32name;
document.getElementsByClassName("room33link")[0].innerHTML=room33name;
document.getElementsByClassName("room34link")[0].innerHTML=room34name;
document.getElementsByClassName("room35link")[0].innerHTML=room35name;
document.getElementsByClassName("room36link")[0].innerHTML=room36name;
document.getElementsByClassName("room37link")[0].innerHTML=room37name;
document.getElementsByClassName("room38link")[0].innerHTML=room38name;
document.getElementsByClassName("room39link")[0].innerHTML=room39name;
document.getElementsByClassName("room40link")[0].innerHTML=room40name;
document.getElementsByClassName("room41link")[0].innerHTML=room41name;
document.getElementsByClassName("room42link")[0].innerHTML=room42name;
document.getElementsByClassName("room43link")[0].innerHTML=room43name;
document.getElementsByClassName("room44link")[0].innerHTML=room44name;
document.getElementsByClassName("room45link")[0].innerHTML=room45name;
document.getElementsByClassName("room46link")[0].innerHTML=room46name;
document.getElementsByClassName("room47link")[0].innerHTML=room47name;
document.getElementsByClassName("room48link")[0].innerHTML=room48name;
document.getElementsByClassName("room49link")[0].innerHTML=room49name;
document.getElementsByClassName("room50link")[0].innerHTML=room50name;
document.getElementsByClassName("room51link")[0].innerHTML=room51name;
document.getElementsByClassName("room52link")[0].innerHTML=room52name;
document.getElementsByClassName("room53link")[0].innerHTML=room53name;
document.getElementsByClassName("room54link")[0].innerHTML=room54name;
document.getElementsByClassName("room55link")[0].innerHTML=room55name;
document.getElementsByClassName("room56link")[0].innerHTML=room56name;
document.getElementsByClassName("room57link")[0].innerHTML=room57name;
document.getElementsByClassName("room58link")[0].innerHTML=room58name;
document.getElementsByClassName("room59link")[0].innerHTML=room59name;
document.getElementsByClassName("room60link")[0].innerHTML=room60name;
document.getElementsByClassName("room61link")[0].innerHTML=room61name;
document.getElementsByClassName("room62link")[0].innerHTML=room62name;
document.getElementsByClassName("room63link")[0].innerHTML=room63name;
document.getElementsByClassName("room64link")[0].innerHTML=room64name;
document.getElementsByClassName("room65link")[0].innerHTML=room65name;
document.getElementsByClassName("room66link")[0].innerHTML=room66name;
document.getElementsByClassName("room67link")[0].innerHTML=room67name;
document.getElementsByClassName("room68link")[0].innerHTML=room68name;
document.getElementsByClassName("room69link")[0].innerHTML=room69name;
document.getElementsByClassName("room70link")[0].innerHTML=room70name;
document.getElementsByClassName("room71link")[0].innerHTML=room71name;
document.getElementsByClassName("room72link")[0].innerHTML=room72name;
document.getElementsByClassName("room73link")[0].innerHTML=room73name;
document.getElementsByClassName("room74link")[0].innerHTML=room74name;
document.getElementsByClassName("room75link")[0].innerHTML=room75name;
document.getElementsByClassName("room76link")[0].innerHTML=room76name;
document.getElementsByClassName("room77link")[0].innerHTML=room77name;
document.getElementsByClassName("room78link")[0].innerHTML=room78name;
document.getElementsByClassName("room79link")[0].innerHTML=room79name;
document.getElementsByClassName("room80link")[0].innerHTML=room80name;
document.getElementsByClassName("room81link")[0].innerHTML=room81name;
document.getElementsByClassName("room82link")[0].innerHTML=room82name;
document.getElementsByClassName("room83link")[0].innerHTML=room83name;
document.getElementsByClassName("room84link")[0].innerHTML=room84name;
document.getElementsByClassName("room85link")[0].innerHTML=room85name;
document.getElementsByClassName("room86link")[0].innerHTML=room86name;
document.getElementsByClassName("room87link")[0].innerHTML=room87name;
document.getElementsByClassName("room88link")[0].innerHTML=room88name;
document.getElementsByClassName("room89link")[0].innerHTML=room89name;
document.getElementsByClassName("room90link")[0].innerHTML=room90name;
document.getElementsByClassName("room91link")[0].innerHTML=room91name;
document.getElementsByClassName("room92link")[0].innerHTML=room92name;
document.getElementsByClassName("room93link")[0].innerHTML=room93name;
document.getElementsByClassName("room94link")[0].innerHTML=room94name;
document.getElementsByClassName("room95link")[0].innerHTML=room95name;
document.getElementsByClassName("room96link")[0].innerHTML=room96name;
document.getElementsByClassName("room97link")[0].innerHTML=room97name;
document.getElementsByClassName("room98link")[0].innerHTML=room98name;
document.getElementsByClassName("room99link")[0].innerHTML=room99name;
document.getElementsByClassName("room100link")[0].innerHTML=room100name;
console.info('room links'); 
}

function doorWay(x,y)
{


document.getElementById(x).style.display = 'block'; document.getElementById(y).style.display = 'none' ;
console.info('door used'); 
}
